package main

import (
	"bufio"
	"encoding/json"
	"io"
	"net"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
	"testing"
	"time"
)

// fakeSMTP is a minimal SMTP server (no TLS, no auth) that records messages.
type fakeSMTP struct {
	ln       net.Listener
	mu       sync.Mutex
	msgs     []smtpMsg
	rejectTo string
}

type smtpMsg struct {
	from string
	rcpt []string
	data string
}

func newFakeSMTP(t *testing.T) *fakeSMTP {
	ln, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatal(err)
	}
	f := &fakeSMTP{ln: ln}
	go func() {
		for {
			c, err := ln.Accept()
			if err != nil {
				return
			}
			go f.serve(c)
		}
	}()
	t.Cleanup(func() { ln.Close() })
	return f
}

func (f *fakeSMTP) port() int { return f.ln.Addr().(*net.TCPAddr).Port }

func (f *fakeSMTP) serve(c net.Conn) {
	defer c.Close()
	r := bufio.NewReader(c)
	say := func(s string) { _, _ = io.WriteString(c, s+"\r\n") }
	say("220 fake ESMTP")
	var m smtpMsg
	for {
		line, err := r.ReadString('\n')
		if err != nil {
			return
		}
		cmd := strings.ToUpper(strings.TrimSpace(line))
		switch {
		case strings.HasPrefix(cmd, "EHLO"), strings.HasPrefix(cmd, "HELO"):
			say("250 fake")
		case strings.HasPrefix(cmd, "MAIL FROM:"):
			m = smtpMsg{from: strings.Trim(strings.TrimSpace(line)[10:], "<>")}
			say("250 OK")
		case strings.HasPrefix(cmd, "RCPT TO:"):
			addr := strings.Trim(strings.TrimSpace(line)[8:], "<>")
			f.mu.Lock()
			reject := f.rejectTo != "" && addr == f.rejectTo
			f.mu.Unlock()
			if reject {
				say("550 no such user")
				continue
			}
			m.rcpt = append(m.rcpt, addr)
			say("250 OK")
		case cmd == "DATA":
			say("354 go ahead")
			var b strings.Builder
			for {
				l, err := r.ReadString('\n')
				if err != nil {
					return
				}
				if l == ".\r\n" {
					break
				}
				b.WriteString(l)
			}
			m.data = b.String()
			f.mu.Lock()
			f.msgs = append(f.msgs, m)
			f.mu.Unlock()
			say("250 queued")
		case cmd == "QUIT":
			say("221 bye")
			return
		default:
			say("250 OK")
		}
	}
}

func (f *fakeSMTP) messages() []smtpMsg {
	f.mu.Lock()
	defer f.mu.Unlock()
	return append([]smtpMsg(nil), f.msgs...)
}

// fakePwPush records pushes and answers like an open source instance.
type fakePwPush struct {
	mu     sync.Mutex
	pushes []map[string]any
	auth   []string
}

func (p *fakePwPush) serve(t *testing.T) *httptest.Server {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch {
		case r.Method == http.MethodGet && r.URL.Path == "/api/v2/version":
			_, _ = w.Write([]byte(`{"application_version":"2.14.1","api_version":"2.1","edition":"oss","features":{"anonymous_access":true}}`))
		case r.Method == http.MethodPost && r.URL.Path == "/api/v2/pushes":
			var body struct {
				Push map[string]any `json:"push"`
			}
			_ = json.NewDecoder(r.Body).Decode(&body)
			p.mu.Lock()
			p.pushes = append(p.pushes, body.Push)
			p.auth = append(p.auth, r.Header.Get("Authorization"))
			n := len(p.pushes)
			p.mu.Unlock()
			w.WriteHeader(201)
			_, _ = w.Write([]byte(`{"url_token":"tok` + strconv.Itoa(n) + `","html_url":"https://pw.example.com/p/tok` + strconv.Itoa(n) + `/r"}`))
		default:
			http.NotFound(w, r)
		}
	}))
	t.Cleanup(srv.Close)
	return srv
}

const welcomeHTML = `<p>Hola {{ .Payload.billing.first_name }},</p>
<p>Tu web: <a href="{{ .Output.SITE_URL }}">{{ .Output.SITE_URL }}</a></p>
<p>Usuario: <b>{{ .Output.USERNAME }}</b> · <a href="{{ .Links.PASSWORD }}">ver contraseña</a></p>
<p>Pedido #{{ .ResourceID }} ({{ .Params.PLAN }}). Password field in template: [{{ .Output.PASSWORD }}]</p>`

func TestWelcomeEmailWithPwPushLink(t *testing.T) {
	smtpSrv := newFakeSMTP(t)
	pw := &fakePwPush{}
	pwSrv := pw.serve(t)
	tmpl := filepath.Join(t.TempDir(), "welcome.html")
	_ = os.WriteFile(tmpl, []byte(welcomeHTML), 0o600)
	t.Setenv("TEST_PW_TOKEN", "pw-token")

	// Generated by the script, as a real one would (not written in the config).
	script := `pw=$(echo czNjcjN0LVA0c3M= | base64 -d); printf 'SITE_URL=https://c1234.nimbox360.com\nUSERNAME=c1234\nPASSWORD="%s"\n' "$pw" > "$DEPLOY_OUTPUT"`
	e := newWooEnv(t, script, `
[deploy.shop.params]
PLAN = { from = "line_items[0].sku", enum = ["basic", "pro"] }
[deploy.shop.email]
to_from = "billing.email"
bcc = ["altas@nimbox360.com"]
subject = "Tu hosting está listo — pedido #{{ .ResourceID }}"
template = "`+tmpl+`"
secrets = ["PASSWORD"]
`, `[smtp]
host = "127.0.0.1"
port = `+strconv.Itoa(smtpSrv.port())+`
tls = "none"
from = "Nimbox360 <hola@nimbox360.com>"

[pwpush]
url = "`+pwSrv.URL+`"
token_env = "TEST_PW_TOKEN"
expire_after_views = 2
expire_after_days = 7
`)
	body := `{"id":1234,"status":"processing","billing":{"email":"ana@example.com","first_name":"Ana"},"line_items":[{"sku":"pro"}]}`
	if rec := e.woo(t, body, wooOpts{delivery: "w1"}); rec.Code != http.StatusAccepted {
		t.Fatalf("%d %s", rec.Code, rec.Body)
	}
	st := e.waitIdleName(t, "shop")
	if st.Status != StatusSuccess {
		t.Fatalf("state %+v", st)
	}
	msgs := smtpSrv.messages()
	if len(msgs) != 1 {
		t.Fatalf("%d messages", len(msgs))
	}
	m := msgs[0]
	if m.from != "hola@nimbox360.com" || strings.Join(m.rcpt, ",") != "ana@example.com,altas@nimbox360.com" {
		t.Fatalf("envelope %s → %v", m.from, m.rcpt)
	}
	for _, want := range []string{
		"To: <ana@example.com>",
		"Subject: =?utf-8?q?Tu_hosting_est=C3=A1_listo_=E2=80=94_pedido_#1234?=",
		"multipart/alternative",
		"Content-Type: text/plain",
		"Content-Type: text/html",
		"https://pw.example.com/p/tok1/r",
		"Hola Ana",
		"Pedido #1234 (pro)",
	} {
		if !strings.Contains(m.data, want) && !strings.Contains(strings.ReplaceAll(m.data, "=\r\n", ""), want) {
			t.Errorf("message missing %q:\n%s", want, m.data)
		}
	}
	if strings.Contains(m.data, "s3cr3t") || strings.Contains(m.data, "Bcc") {
		t.Errorf("message leaks the password or the bcc:\n%s", m.data)
	}
	if !strings.Contains(m.data, "Password field in template: []") {
		t.Errorf("the raw secret should be removed from .Output")
	}

	pw.mu.Lock()
	push, auth := pw.pushes[0], pw.auth[0]
	pw.mu.Unlock()
	if push["payload"] != "s3cr3t-P4ss" || push["expire_after_views"] != float64(2) || push["expire_after_days"] != float64(7) ||
		push["retrieval_step"] != true || push["expire_after_duration"] != nil || !strings.Contains(push["note"].(string), "shop #1234") || auth != "Bearer pw-token" {
		t.Errorf("push %v auth %q", push, auth)
	}

	logText := readLatest(t, e, "shop")
	if !strings.Contains(logText, "email: sent to a***@example.com, a***@nimbox360.com (welcome.html, 1 secret links)") {
		t.Errorf("log:\n%s", logText)
	}
	if strings.Contains(logText, "s3cr3t") || strings.Contains(logText, "ana@example.com") {
		t.Errorf("log leaks:\n%s", logText)
	}
	if left, _ := filepath.Glob(filepath.Join(e.logDir, "shop", ".*output")); len(left) > 0 {
		t.Errorf("output file left: %v", left)
	}

	// The same order again (a replay): no second email.
	if rec := e.woo(t, strings.Replace(body, "processing", "completed", 1), wooOpts{delivery: "w2"}); rec.Code != http.StatusAccepted {
		t.Fatalf("%d %s", rec.Code, rec.Body)
	}
	e.waitIdleName(t, "shop")
	if n := len(smtpSrv.messages()); n != 1 || !strings.Contains(readLatest(t, e, "shop"), "already sent for #1234") {
		t.Errorf("%d messages after the replay:\n%s", n, readLatest(t, e, "shop"))
	}
}

func TestEmailOutboxAndRetry(t *testing.T) {
	smtpSrv := newFakeSMTP(t)
	smtpSrv.rejectTo = "ana@example.com"
	tmpl := filepath.Join(t.TempDir(), "done.txt")
	_ = os.WriteFile(tmpl, []byte("Listo: {{ .Output.SITE_URL }}\n"), 0o600)
	srv, got := recorder(t)
	t.Setenv("TEST_NOTIFY_URL", srv.URL)
	e := newWooEnv(t, `echo '{"SITE_URL":"https://x.example.com"}' > "$DEPLOY_OUTPUT"`, `
[deploy.shop.email]
to_from = "billing.email"
subject = "Listo"
template = "`+tmpl+`"
`, `[smtp]
host = "127.0.0.1"
port = `+strconv.Itoa(smtpSrv.port())+`
tls = "none"
from = "hola@nimbox360.com"
[notify]
format = "json"
url_env = "TEST_NOTIFY_URL"
`)
	e.woo(t, `{"id":7,"status":"processing","billing":{"email":"ana@example.com"}}`, wooOpts{delivery: "o1"})
	st := e.waitIdleName(t, "shop")
	if st.Status != StatusSuccess {
		t.Fatalf("the deploy itself worked: %+v", st)
	}
	files, _ := filepath.Glob(filepath.Join(e.logDir, "shop", "outbox", "*.json"))
	if len(files) != 1 {
		t.Fatalf("outbox %v\n%s", files, readLatest(t, e, "shop"))
	}
	if info, _ := os.Stat(files[0]); info.Mode().Perm() != 0o600 {
		t.Errorf("outbox mode %v", info.Mode().Perm())
	}
	if !strings.Contains(readLatest(t, e, "shop"), "kept in") {
		t.Errorf("log:\n%s", readLatest(t, e, "shop"))
	}
	deadline := time.Now().Add(5 * time.Second)
	for time.Now().Before(deadline) && len(got()) == 0 {
		time.Sleep(20 * time.Millisecond)
	}
	if n := got(); len(n) == 0 || !strings.Contains(func() string { b, _ := json.Marshal(n[0].body); return string(b) }(), "nimdeploy mail retry") {
		t.Errorf("team not told: %+v", n)
	}

	// Fixed: retry sends it and marks the order as emailed.
	smtpSrv.mu.Lock()
	smtpSrv.rejectTo = ""
	smtpSrv.mu.Unlock()
	if code := mailRetry(e.cfg, nil); code != 0 {
		t.Fatalf("retry exit %d", code)
	}
	if msgs := smtpSrv.messages(); len(msgs) != 1 || !strings.Contains(msgs[0].data, "Listo: https://x.example.com") {
		t.Fatalf("messages %+v", msgs)
	}
	if left, _ := filepath.Glob(filepath.Join(e.logDir, "shop", "outbox", "*.json")); len(left) != 0 {
		t.Errorf("outbox not emptied: %v", left)
	}
	if sent, _ := filepath.Glob(filepath.Join(e.logDir, "shop", "mail-sent", "*")); len(sent) != 1 {
		t.Errorf("once marker %v", sent)
	}
}

func TestReadOutputAndHTMLToText(t *testing.T) {
	dir := t.TempDir()
	kv := filepath.Join(dir, "kv")
	_ = os.WriteFile(kv, []byte("# results\nA=1\nB = \"two words\"\nC='x=y'\n\nbad line\n"), 0o600)
	got, err := readOutput(kv)
	if err != nil || got["A"] != "1" || got["B"] != "two words" || got["C"] != "x=y" || len(got) != 3 {
		t.Fatalf("kv %v %v", got, err)
	}
	js := filepath.Join(dir, "js")
	_ = os.WriteFile(js, []byte(`{"URL":"https://a","PORT":8083,"OK":true,"NESTED":{"x":1}}`), 0o600)
	got, err = readOutput(js)
	if err != nil || got["URL"] != "https://a" || got["PORT"] != "8083" || got["OK"] != "true" || got["NESTED"] != "" {
		t.Fatalf("json %v %v", got, err)
	}
	if got, err := readOutput(filepath.Join(dir, "missing")); err != nil || len(got) != 0 {
		t.Fatalf("missing file %v %v", got, err)
	}
	text := htmlToText(`<style>p{}</style><p>Hola <b>Ana</b>,</p><p>Entra: <a href="https://x/r">aquí</a></p><br>Fin &amp; ya<table><tr><td>Usuario</td><td>c1</td></tr></table>`)
	if text != "Hola Ana,\nEntra: aquí (https://x/r)\n\nFin & yaUsuario: c1" {
		t.Errorf("text %q", text)
	}
	if maskEmail("ana@example.com") != "a***@example.com" || maskEmail("bad") != "***" {
		t.Error("maskEmail")
	}
}

func TestCLIPwPush(t *testing.T) {
	pw := &fakePwPush{}
	srv := pw.serve(t)
	e := newEnv(t, `true`, `[pwpush]
url = "`+srv.URL+`"
`)
	r, w, _ := os.Pipe()
	_, _ = w.WriteString("hunter2\n")
	w.Close()
	old := os.Stdin
	os.Stdin = r
	defer func() { os.Stdin = old }()
	if code := cliPwPush(e.cfg, filepath.Join(e.dir, "secrets.env"), []string{"-views", "1", "-note", "test"}); code != 0 {
		t.Fatalf("exit %d", code)
	}
	pw.mu.Lock()
	defer pw.mu.Unlock()
	if len(pw.pushes) != 1 || pw.pushes[0]["payload"] != "hunter2" || pw.pushes[0]["expire_after_views"] != float64(1) || pw.auth[0] != "" {
		t.Fatalf("pushes %v auth %v", pw.pushes, pw.auth)
	}
}

func TestEmailConfigValidation(t *testing.T) {
	tmpl := filepath.Join(t.TempDir(), "t.html")
	_ = os.WriteFile(tmpl, []byte("{{ .Output.X }}"), 0o600)
	bad := filepath.Join(t.TempDir(), "bad.html")
	_ = os.WriteFile(bad, []byte("{{ .Output.X "), 0o600)
	base := "[logging]\ndirectory = \"/tmp/x\"\n"
	smtp := "[smtp]\nhost = \"smtp.example.com\"\nfrom = \"a@example.com\"\n"
	dep := "[deploy.s]\npath = \"/hooks/s\"\nrepository = \"a/b\"\nsecret_env = \"S\"\ncommand = \"/bin/true\"\n[deploy.s.email]\nsubject = \"x\"\nto = [\"b@example.com\"]\n"
	cases := map[string]string{
		dep + "template = \"" + tmpl + "\"\n":                                       "needs an [smtp] section",
		smtp + dep + "template = \"rel.html\"\n":                                    "absolute path",
		smtp + dep + "template = \"" + bad + "\"\n":                                 "template:",
		smtp + dep + "template = \"" + tmpl + "\"\non = \"sometimes\"\n":            "on must be",
		smtp + dep + "template = \"" + tmpl + "\"\nsecrets = [\"lower\"]\n":         "UPPER_CASE",
		"[smtp]\nhost = \"smtp.example.com\"\nfrom = \"not an address\"\n":          "smtp: from",
		"[smtp]\nhost = \"smtp.example.com\"\nfrom = \"a@b.c\"\ntls = \"none\"\n":   "only allowed for a local relay",
		"[smtp]\nhost = \"smtp.example.com\"\nfrom = \"a@b.c\"\nuser_env = \"U\"\n": "go together",
		"[pwpush]\nurl = \"http://pw.example.com\"\n":                               "must be https",
		"[pwpush]\nexpire_after_duration = 40\n":                                    "index 0-17",
	}
	for extra, want := range cases {
		path := filepath.Join(t.TempDir(), "c.toml")
		content := base + extra
		if !strings.Contains(extra, "[deploy.") {
			content += "[deploy.z]\npath = \"/hooks/z\"\nrepository = \"a/b\"\nsecret_env = \"S\"\ncommand = \"/bin/true\"\n"
		}
		_ = os.WriteFile(path, []byte(content), 0o600)
		if _, err := LoadConfig(path); err == nil || !strings.Contains(err.Error(), want) {
			t.Errorf("%q: got %v, want %q", extra, err, want)
		}
	}
	// Defaults: STARTTLS on 587, 465 means TLS.
	path := filepath.Join(t.TempDir(), "c.toml")
	_ = os.WriteFile(path, []byte(base+"[smtp]\nhost = \"smtp.example.com\"\nport = 465\nfrom = \"a@b.c\"\n"+dep+"template = \""+tmpl+"\"\n"), 0o600)
	cfg, err := LoadConfig(path)
	if err != nil {
		t.Fatal(err)
	}
	if cfg.SMTP.TLS != "tls" || cfg.PwPush.URL != defaultPwPushURL || cfg.PwPush.ExpireAfterViews != 3 || cfg.Deploy["s"].Email.On != "success" {
		t.Fatalf("defaults %+v %+v", cfg.SMTP, cfg.PwPush)
	}
}
